### ISSUE TITLE
Add some extra reward to bot when it gets to the end

### ISSUE THREAD

**Issue by wmartins** [famw/SpelunkBots#19]
Some bots may find out that going away from the end is better then entering in the exit door (this is because the reward is based on the distance traveled). So, we need to add some extra reward to make entering on the exit door more attractive then jumping it.

**Comment by wmartins** [comment]
@martinduartemore, can you confirm if is this implemented?

So we can close this issue! :)

**Comment by martinduartemore** [comment]
Yes, this is implemented. When the bot reaches the end, it gets maximum distance fitness.
